### ISSUE TITLE
[FEAT]:Adding animation effects to projects,testimonials and certificates section

### ISSUE THREAD

**Issue by ShaikArshidBanu** [SnowScriptWinterOfCode/PortfolioCreations#93] opened 2024-01-07 17:32 UTC
Enhancing the website by adding animation effects to projects,testimonials and certificates section.

Proposed enhancement:
https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/112767165/9f97e097-8c53-4ec0-bf20-2aee00016d30

**Comment by ShaikArshidBanu** [comment] 2024-01-07 17:32
@ayushichoudhary-19 assign this issue to me.

**Comment by ayushichoudhary-19** [comment] 2024-01-07 17:35
@ShaikArshidBanu The issue is now assigned to you!

**Closed as completed** 2024-01-08 16:50 UTC
