### ISSUE TITLE
Adding and designing the profile image to portfolio

### ISSUE THREAD

**Issue by Riddhi050803** [SnowScriptWinterOfCode/PortfolioCreations#5] opened 2023-12-28 15:48 UTC
Adding image to the portfolio will make it attractive and effective .Designing ie. providing it the appropriate shape ,margin and padding & shadow etc. is equally important aspect .
![Screenshot 2023-12-28 211640](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/122264483/d5fcf8af-dc74-4ac4-afc4-878724df30b4)

**Comment by Nitya-Pasrija** [comment] 2023-12-28 15:48
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!

**Comment by Ipshita-Tandon** [comment] 2023-12-29 04:14
I would like to work on this issue, please assign it to me
Adding and designing the profile image to portfolio #5

**Comment by navyasaini** [comment] 2023-12-29 13:55
Hey, I would love to work on this issue. I'm planning to add a slideshow of images that will include the person's pic, meetups group photos and other achievements. Please assign this issue to me. 
@Nitya-Pasrija

**Comment by Kalpana8055** [comment] 2023-12-30 05:50
@Nitya-Pasrija i would like to work on it please assign it to me

**Comment by priyagupta20044** [comment] 2023-12-31 12:37
@Nitya-Pasrija Please assign me this. I would like to add the png of the person with moving animation on hover.

**Comment by Nitya-Pasrija** [comment] 2023-12-31 14:03
Would be assigning it to @Ipshita-Tandon

@priyagupta20044 and @Kalpana8055, please reach out to @Ipshita-Tandon, in case you wish to work together on this one :)

**Comment by ayushichoudhary-19** [comment] 2024-01-02 09:59
Hi @Ipshita-Tandon,
Hope you're doing well! We noticed that the issue is still assigned to you, and it has been a few days since it was raised. 
If you're facing any challenges or need assistance, feel free to ask for help. Also, if you think you won't be able to address this issue at the moment, please let us know soon so that we can either help or consider reassigning it.

However, it's crucial to emphasize that a **pull request must be submitted to address this issue by midnight**. This is necessary to ensure that everyone has an equal opportunity to contribute.

Looking forward to your contributions!

**Comment by VenusCh001** [comment] 2024-01-03 10:04
Kindly assign this issue to me

thankyou
VenusCh001

@ayushichoudhary-19

**Closed as completed** 2024-01-05 15:39 UTC
Labels: good first issue, user-experience, assigned
