### ISSUE TITLE
Bug Fixes and Code Redundancy

### ISSUE THREAD

**Issue by hars-21** [SnowScriptWinterOfCode/PortfolioCreations#79] opened 2024-01-06 16:36 UTC
I just viewed the code and ended up on a conclusion that there are minor bugs.
Code is repeated that makes code complicated and it needs to be fixed.

**Comment by hars-21** [comment] 2024-01-06 17:37
Please assign this to me.

**Comment by ayushichoudhary-19** [comment] 2024-01-07 17:34
@Harshil-Gupta21, the issue is now assigned to you!

**Closed as completed** 2024-01-13 07:31 UTC
Labels: bug, enhancement, assigned, refactoring
