### ISSUE TITLE
Fix testimonial section.

### ISSUE THREAD

**Issue by Mahak008** [SnowScriptWinterOfCode/PortfolioCreations#88] opened 2024-01-07 12:51 UTC
### Issue Description

Testimonial section doesn't align with the page neither in laptop view nor in mobile view.

### Additional Context

⚠️ **Warning**: Before submitting, please check for existing issues to avoid duplicates. If you find a related issue, consider adding your insights or upvoting the existing one. Thank you!

**Comment by ayushichoudhary-19** [comment] 2024-01-07 18:07
Hi @Mahak008. The issue template is there to help gather detailed information on the issue and is not supposed to be submitted as it is! However, in this submission, crucial details are missing, including a clear description of the issue and your ideas for improvement. Please fill it out properly before we move forward. Provide the necessary details so we can consider assigning this issue.

**Comment by ayushichoudhary-19** [comment] 2024-01-13 06:54
@Mahak008, what's the status of your PR?

**Comment by hars-21** [comment] 2024-01-13 18:06
Can I contribute? If open for all and not currently assigned.

**Comment by ayushichoudhary-19** [comment] 2024-01-14 06:35
> Can I contribute? If open for all and not currently assigned.

The issue is now assigned to you! Also, @Harshil-Gupta21, it's not just about the responsiveness; the design itself does not look elegant, especially the emojis used. I want it to be changed entirely into something cleaner and refined while ensuring responsiveness. Please look into this before submitting a PR.

**Comment by hars-21** [comment] 2024-01-14 06:40
Okay will try something good and better that aligns with the theme of our website.

**Closed as completed** 2024-01-20 09:21 UTC
Labels: assigned
