### ISSUE TITLE
[Feat]: ADD dark mode feature

### ISSUE THREAD

**Issue by bj-jiwrajka** [SnowScriptWinterOfCode/PortfolioCreations#95] opened 2024-01-08 05:52 UTC
The website should also be available with dark mode

**Comment by bj-jiwrajka** [comment] 2024-01-08 05:52
@ayushichoudhary-19 can I work on it?

**Comment by Nitya-Pasrija** [comment] 2024-01-08 05:53
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by ayushichoudhary-19** [comment] 2024-01-12 04:45
@bj-jiwrajka, the issue is now assigned to you.

**Comment by ayushichoudhary-19** [comment] 2024-01-20 09:28
@bj-jiwrajka What's the status of the pull request? Please submit it by midnight today, or else we'll have to open the issue for other contributors.

**Comment by hars-21** [comment] 2024-01-22 18:54
Assign me Please

**Closed as completed** 2024-01-23 15:17 UTC
Labels: enhancement, user-experience, assigned
