### ISSUE TITLE
add skill section

### ISSUE THREAD

**Issue by Kalpana8055** [SnowScriptWinterOfCode/PortfolioCreations#11] opened 2023-12-29 08:32 UTC
add skills section and also show the percentage of skills 
![WhatsApp Image 2023-12-29 at 1 58 39 PM](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/154818080/11cee272-33f6-46e4-bb33-47623c668dad)

**Comment by Nitya-Pasrija** [comment] 2023-12-29 08:33
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!

**Comment by ayushichoudhary-19** [comment] 2024-01-01 15:23
@Kalpana8055 , thank you for raising this issue. It seems similar to #7 and #6. To avoid duplication, let's continue the discussion on the existing issue. If you have any additional insights or details to add, please do so there. Thanks!

(Closing this as a duplicate of  #7 and #6)

**Closed as not planned** 2024-01-01 15:24 UTC
Labels: duplicate
